### ISSUE TITLE
Configuration - incorrect documentation  

### ISSUE THREAD

**Issue by dilrajsachdev** [vstoykov/django-clamd#1]
In document, it states the default configuration are
 CLAMD_SOCKET = '/var/run/clamav/clamd.ctl'
CLAMD_USE_TCP = False
CLAMD_TCP_SOCKET = 3310
CLAMD_TCP_ADDR = '127.0.0.1'

But it should be 
CLAMD_SOCKET = '/var/run/clamav/clamd.ctl'
CLAMD_USE_TCP = False
CLAMD_TCP_PORT = 3310
CLAMD_TCP_SOCKET = '127.0.0.1'

Thanks

**Comment by vstoykov** [comment]
Thanks. I will fix it.

**Comment by vstoykov** [comment]
Actually I will change it to respect the documentation because names there are more close to real config vars in clamd.conf file: `TCPSocket`, `TCPAddr`

**Comment by dilrajsachdev** [comment]
Yes that will be better, thanks

**Comment by vstoykov** [comment]
There is new version on PyPi (0.3.2).
