### ISSUE TITLE
Please push the latest updates to pypi

### ISSUE THREAD

**Issue by maksym3d** [vstoykov/django-clamd#17]
Thank you for the wonderful plugin! Can you possibly publish the current version to pypi? I see you have updated the validators.py to import gettext_lazy in place of ugettext_lazy, but pip3 still pulls the original version incompatible with the current Django. Thank you!

**Comment by tomkins** [comment]
A v1.0.0 has been tagged on GitHub, but PyPI still has 0.4.0 as the latest version.

https://github.com/vstoykov/django-clamd/releases/tag/1.0.0
https://pypi.org/project/django-clamd/#history

Would be nice to see the latest version on PyPI.

**Comment by Yelinz** [comment]
Thanks for the work @vstoykov 

A consequence of this is that packages which use django-clamd cannot upgrade their dependencies and release.
Because pypi forbids publishing packages which have dependencies outside of pypi (e.g. installing from 1.0.0 tag on github).

**Comment by vstoykov** [comment]
Hello everyone. The new release is out in PyPi. https://pypi.org/project/django-clamd/1.0.0/ Thank you for your patience.
